IMAGE_BOX = "generic/ubuntu2204"
TIMEZONE_VMS = "America/Sao_Paulo"

Vagrant.configure("2") do |config|

    config.vm.provision "shell", inline: <<-SHELL
    echo "192.168.56.56  master-1" >> /etc/hosts
    echo "192.168.56.61  worker-1" >> /etc/hosts
    SHELL

    config.vm.provision "shell", path: "scripts/common.sh", env: { "TIMEZONE_VMS" => "#{TIMEZONE_VMS}" }

    (1..1).each do |i|
        config.vm.define "master-#{i}" do |k8s|
            k8s.vm.box = "#{IMAGE_BOX}"
            k8s.vm.hostname = "master-#{i}"
            k8s.vm.network "private_network", ip: "192.168.56.56"

            k8s.ssh.insert_key = false
            k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

            k8s.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 2
              vb.memory = "2048"
            end
        end
    end

    (1..1).each do |i|
        config.vm.define "worker-#{i}" do |k8s|
            k8s.vm.box = "#{IMAGE_BOX}"
            k8s.vm.hostname = "worker-#{i}"
            k8s.vm.network "private_network", ip: "192.168.56.6#{i}"

            k8s.ssh.insert_key = false
            k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

            k8s.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 1
              vb.memory = "1024"
            end
        end
    end
end
